### ISSUE TITLE
How to get the sample image?

### ISSUE THREAD

**Issue by newforrestgump001** [reunanen/tinyseg#1]
Could I have the sample image to have a try? Thanks!

**Comment by reunanen** [comment]
You need to install [Git LFS](https://git-lfs.github.com/).

**Comment by newforrestgump001** [comment]
Thank you a lot !!!
tinyseg/test-images$ git lfs pull
Git LFS: (0 of 12 files) 0 B / 4.34 MB                                                                                                                 
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/reunanen/tinyseg.git/info/lfs'

**Comment by reunanen** [comment]
Ok, so I'm over my LFS quota. Well, I just put them [here](https://www.dropbox.com/sh/sjculmccrgdao3o/AAA3WmXfcSMUPs9r29SFS06Da).
