### ISSUE TITLE
How to report issue for https://github.com/reunanen/dlib.git?

### ISSUE THREAD

**Issue by newforrestgump001** [reunanen/tinyseg#2]
Please tell me how to report a new issue for the repo:
https://github.com/reunanen/dlib.git
Thanks!

**Comment by reunanen** [comment]
Enabled issues. So, here: https://github.com/reunanen/dlib/issues

**Comment by reunanen** [comment]
Although, if it's related to the upstream dlib, maybe you'll want to do it here instead: https://github.com/davisking/dlib/issues
